### ISSUE TITLE
Four screen mode true for non cases.

### ISSUE THREAD

**Issue by skatiyar** [satoshinm/nes-file#1]
https://github.com/satoshinm/nes-file/blob/f7dff0b0dc301c75f49106b84fafd22eed83fda3/nes-file.js#L32
Extra `&` gives false positive for files.
Should be
```
info.four_screen_mode = !!(flags6 & 8); 
```

**Comment by satoshinm** [comment]
Good catch! Silly typo...

I've added you as a collaborator, do you want to make this fix? Haven't looked at this project in a while...
